---
AWSTemplateFormatVersion: '2010-09-09'
Description: Sample EC2 instance for doj_labs

Parameters:

  ImageId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'

  InstanceType:
    Type: String
    AllowedValues:
      - t2.micro
      - t2.nano

  SecurityGroupId:
    Type: String
    Description: Id of the security group to allow port 80 access

  SubnetId:
    Type: String
    Description: Id for a public subnet to place the EC2 instance

  Message:
    Type: String
    Description: Message for the Web Server

Resources:

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref SecurityGroupId
      SubnetId: !Ref SubnetId
      UserData:
        Fn::Base64: !Sub |
            #!/bin/bash
            sudo yum -y update
            sudo yum install -y httpd
            mkdir -p /var/www/html
            echo "<html><h1>${Message}</h1></html>" | sudo tee /var/www/html/index.html
            chown -R apache:apache /var/www/html
            touch /var/www/html/index.html
            service httpd start
